name: MLOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install notebook nbconvert

      - name: Verificar arquivos no diretório
        run: |
          echo "Conteúdo do diretório atual:"
          ls -la
          echo "Subdiretórios:"
          ls -R

      - name: Executar notebook com debug
        run: |
          jupyter nbconvert --to notebook --execute notebook_mlops_pipeline.ipynb --output executed_notebook.ipynb --debug

      - name: Verificar modelo salvo
        run: |
          ls -l model.joblib || echo "Arquivo model.joblib não encontrado"
